<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite ignored="0" hostname="PC-75" failures="1" tests="2" name="Test" time="46.01" errors="0" timestamp="2023-10-04T19:26:35 IST">
  <testcase classname="KycPageTC.KYCPage" name="KYCFormFill" time="37.303"/>
  <testcase classname="KycPageTC.KYCPage" name="test2" time="0.027">
    <failure type="java.lang.AssertionError" message="The following asserts failed:
	expected [s2] but found [s1]">
      <![CDATA[java.lang.AssertionError: The following asserts failed:
expected [s2] but found [s1]
at KycPageTC.KYCPage.test2(KYCPage.java:474)
at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
at java.base/java.lang.Thread.run(Thread.java:833)
... Removed 10 stack frames]]>
    </failure>
  </testcase> <!-- test2 -->
</testsuite> <!-- Test -->
